apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: us.icr.io/vthink/nodewebapp
      ports:
        - containerPort: 5000
          protocol: TCP
