apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    hitapp: dbtutorial
spec:
  containers:
    - name: redis
      image: redis:latest # Use the docker image
      ports:
        - containerPort: 6379
          protocol: TCP
